name: packaging-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - sphinx
  - nbsphinx
  - jupyterlab-myst
  - pytest
  - pytest-cov
  - pytest-mpl
  - pylint
  - ruff
  - build
  - conda-build
  - anaconda-client