[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "splinart"
requires-python = ">=3.8"
dependencies = ["numpy", "matplotlib"]

[tool.setuptools.packages.find]
include = ["splinart*"]
